// localization/ar.js
export const ar = {
    english: "الإنجليزية",
    arabic: "العربية",
    headTitle: "متجر المزارع",
    home: "الرئيسية",
    about: "من نحن",
    profile: "الملف الشخصي",
    orders: "طلباتي",
    cart: "العربة",
    login: "تسجيل الدخول",
    addAccount: "إضافة حساب آخر",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    loading: "جار التحميل...",
    tryAgain: "حاول مرة أخرى",
    somthingWentWrong: "لقد حدث خطأ!",
    // home page
    "From Our Store to Your Door": "من متجرنا إلى بابك",
    "Fast & smooth shopping experience": "تجربة تسوق سريعة وسلسة للأسر.",
    prevArrow: "السابق",
    nextArrow: "التالي",
    order: "أطلب الآن",
    featuredProducts: "منتجات مميزة",
    topDeals: "أفضل العروض",
    bestSellers: "الأكثر مبيعًا",
    newArrivals: "وصل حديثآ",
    whyChooseUs: "لماذا تختارنا",
    allRightsReserved: "جميع الحقوق محفوظة.",
    searchProductsOrCategories: "ابحث عن منتجات أو فئات...",
    by: "بواسطة",
    viewAllFeatured: "عرض جميع منتجاتنا المميزة",
    viewAllDeals: "عرض جميع أفضل عروضنا",
    viewAllBestSellers: "عرض المنتجات الأكثر مبيعًا",
    viewAllNewArrivals: "عرض جميع المنتجات الجديدة",
    new: "جديد",
    addToCart: "أضف إلى العربة",
    off: "% خصم",
    noResultsFound: "لا توجد نتائج",
    // product/slug page
    uncategorized: "غير مصنف",
    quantity: "الكمية",
    soldBy: "يباع بواسطة",
    relatedProducts: "منتجات ذات صلة",
    shopByCategory: "تسوق حسب الفئة",
    // category/[slug] page
    categoryHeaderDescription: "استكشف مجموعة واسعة من المنتجات الطازجة والعضوية في هذه الفئة.",
    noProductsInCategory: "لا توجد منتجات في هذه الفئة.",
    loadMore: "تحميل المزيد",
    endOfResults: "نهاية النتائج",
    leftInStock: "متبقي في المخزون",
    outOfStock: "منتهية المخزون",
    // login
    welcomeMsg: "أهلآ بكم في فارمرز ماركت",
    slogan: "طازج، محلي، ومستدام—قم بتسجيل الدخول لاستكشاف أفضل المنتجات.",
    signUpQuestion: "ليس لديك حساب؟",
    register: "انشىء حساب",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    rememberMe: "تذكرني",
    hidePassword: "إخفاء كلمة المرور",
    showPassword: "إظهار كلمة المرور",
    signInWithGoogle: "تسجيل الدخول بجوجل",
    // login validation
    loginSuccessfullMsg: "تم تسجيل الدخول بنجاح",
    invalidEmail: "البريد الإلكتروني خطأ",
    emailRequired: "البريد الإلكتروني مطلوب",
    passwordLength: "يجب أن تتراوح كلمة المرور بين 8 و 20 حرفًا",
    passwordRequired: "كلمة المرور مطلوبة",
    // register
    firstName: "الاسم الأول",
    lastName: "الاسم الثاني",
    phoneNumber: "رقم الهاتف",
    enterPhoneNumber: "ادخل رقم الهاتف الخاص بك",
    alreadyHaveAnAccountQuestion: "لديك حساب؟",
    // register validation
    registrationSuccessfullMsg: "تم التسجيل بنجاح! يرجى تسجيل الدخول.",
    nameLength: "يجب أن يكون الاسم بين 3 و 30 حرفًا.",
    nameRegexError: "يمكن أن يحتوي الاسم فقط على أحرف وأرقام ومسافات وشرطات (_) و (-)",
    nameRequired: "الاسم مطلوب",
    invalidEmail: "يرجى إدخال بريد إلكتروني صالح",
    emailRequired: "البريد الإلكتروني مطلوب",
    passwordRegexError: "يجب أن تحتوي كلمة المرور على حرف واحد على الأقل وحرف خاص واحد على الأقل",
    phoneNumberRequired: "رقم الهاتف مطلوب",
    phoneNumberRegex: "يجب أن يبدأ رقم الهاتف بـ 010 أو 011 أو 012 أو 015 وأن يكون مكونًا من 11 رقمًا",
    // Register/Login through google provider
    googleSignInError: "فشل تسجيل الدخول عبر جوجل. يرجى المحاولة مرة أخرى.",
    googleAccountEmailInUse: "البريد الإلكتروني لحساب جوجل مستخدم بالفعل. يرجى استخدام بريد إلكتروني مختلف.",
    continueWithGoogle: "المتابعة عبر جوجل",
    // dashboard
    dashboard: "لوحة التحكم",
    welcomeToDashboardMsg: "مرحبًا بك في لوحة التحكم",
    dashboardSlogan:"هنا يمكنك رؤية إحصائياتك ونشاطاتك الأخيرة والمزيد.",
    stats: "الإحصائيات",
    recentActivity: "النشاطات الأخيرة",
    recentOrders: "الطلبات الأخيرة",
    recentReviews: "المراجعات الأخيرة",
    recentMessages: "الرسائل الأخيرة",
    recentProducts: "المنتجات الأخيرة",
    recentUsers: "المستخدمين الأخيرين",
    recentOrders: "الطلبات الأخيرة",
    languageSelector: "اختيار اللغة",
    selectLanguage: "اختر اللغة",
    openToSwitchLanguage: "انقر لتغيير اللغة",
    // dashboard/customers
    customersManagement: "إدارة العملاء",
    customers: "العملاء",
    customersList: "قائمة العملاء",
    createdAt: "تاريخ الإنشاء",
    search: "بحث",
    status: "الحالة",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    all: "الكل",
    active: "نشط",
    inactive: "غير نشط",
    pleaseSubmitToSearch: "يرجى إرسال النموذج للبحث عن العملاء",
    noCustomersFound: "لا توجد عملاء",
    submit: "إرسال",
    reset: "إعادة تعيين",
    dataRetreivedSuccessfully: "تم استرجاع البيانات بنجاح",
    customersDescription: "إدارة حسابات العملاء وعرض تفاصيل العملاء.",
    view: "عرض",
    customersPagination: "تسلسل العملاء في الجدول",
    // dashboard/customers/[id]
    customerNotFound: "العميل غير موجود",
    joinedOn: "انضم في",
    goBack: "العودة",
    customerProfile: "ملف العميل",
    customerDetails: "تفاصيل العميل",
    basicInfo: "المعلومات الأساسية",
    customerOrders: "طلبات العميل",
    contactInformation: "معلومات الاتصال",
    addressInformation: "معلومات العنوان",
    shippingAddress: "عنوان الشحن",
    billingAddress: "عنوان الفاتورة",
    noDefaultShippingAddress: "لا يوجد عنوان شحن افتراضي محدد",
    noDefaultBillingAddress: "لا يوجد عنوان فاتورة افتراضي محدد",
    noAddressProvided: "لم يتم توفير عنوان",
    orderNumber: "رقم الطلب",
    orderDate: "تاريخ الطلب",
    orderStatus: "حالة الطلب",
    orderTotal: "إجمالي الطلب",
    orderDetails: "تفاصيل الطلب",
    orderItems: "عناصر الطلب",
    orderQuantity: "الكمية",
    orderPrice: "السعر",
    orderSubtotal: "المجموع الفرعي",
    orderShipping: "الشحن",
    orderTax: "الضريبة",
    orderTotalAmount: "المبلغ الإجمالي",
    orderActions: "الإجراءات",
    noOrders: "لا توجد طلبات لهذا العميل",
    updating: "جار التحديث...",
    deactivate: "إلغاء التفعيل",
    activate: "تفعيل",
    userStatusUpdatedSuccessfully: "تم تحديث حالة المستخدم بنجاح",
    // Profile
    myAccount: "حسابي",
    personalInfo: "المعلومات الشخصية",
    saveChanges: "حفظ التغييرات",
    profileUpdated: "تم تحديث الملف الشخصي بنجاح",
    profileUpdateFailed: "فشل تحديث الملف الشخصي",
    addresses: "العناوين",
    editAddress: "تعديل العنوان",
    addNewAddress: "إضافة عنوان جديد",
    addressDetails: "تفاصيل العنوان",
    edit: "تعديل",
    viewDetails: "عرض التفاصيل",
    street: "الشارع",
    city: "المدينة",
    state: "الولاية",
    zipCode: "الرمز البريدي",
    country: "البلد",
    isDefaultShipping: "هو عنوان الشحن الافتراضي",
    isDefaultBilling: "هو عنوان الفاتورة الافتراضي",
    save: "حفظ",
    cancel: "إلغاء",
    confirm: "تأكيد",
    defaultShipping: "عنوان الشحن الافتراضي",
    defaultBilling: "عنوان الفاتورة الافتراضي",
    // profile validation
    streetLength: "يجب أن يتراوح طول الشارع بين 3 و 100 حرف",
    streetRequired: "الشارع مطلوب",
    cityLength: "يجب أن يتراوح طول المدينة بين 2 و 50 حرف",
    cityRequired: "المدينة مطلوبة",
    stateLength: "يجب أن يتراوح طول الولاية بين 2 و 50 حرف",
    zipCodeLength: "يجب أن يتراوح طول الرمز البريدي بين 5 و 10 أحرف",
    zipCodeRequired: "الرمز البريدي مطلوب",
    countryRequired: "البلد مطلوب",
    addressSavedSuccessfully: "تم حفظ العنوان بنجاح",
    addressSaveFailed: "فشل حفظ العنوان",
    addressRemovedSuccessfully: "تمت إزالة العنوان بنجاح",
    addressRemoveFailed: "فشل إزالة العنوان",
    // dashboard/categories
    categoriesManagement: "إدارة الفئات",
    categories: "الفئات",
    categoriesList: "قائمة الفئات",
    noCategoriesFound: "لا يوجد فئات",
    addCategory: "إضافة فئة جديدة",
    editCategory: "تعديل الفئة",
    deleteCategory: "مسح الفئة",
    searchCategory: "البحث عن فئة",
    categoryNameEn: "اسم الفئة (بالإنجليزية)",
    categoryNameAr: "اسم الفئة (بالعربية)",
    textColor: "لون النص",
    categoryImage: "صورة الفئة",
    uploadImage: "تحميل الصورة",
    // validation messages
    categoryNameEnRequired: "اسم الفئة (بالإنجليزية) مطلوب",
    categoryNameArRequired: "اسم الفئة (بالعربية) مطلوب",
    invalidImageFormat: "صيغة الصورة غير صالحة. الصيغ المسموح بها: jpg، jpeg، png، gif، webp",
    categoryNameLength: "يجب أن يتراوح اسم الفئة بين 3 و 50 حرفًا",
    categoryNameRegexError: "يمكن أن يحتوي اسم الفئة على أحرف وأرقام ومسافات ورموز: - _ .",
    imageRequired: "صورة الفئة مطلوبة",
    categoryUpdatedSuccessfully: "تم تحديث الفئة بنجاح",
    categoryAddedSuccessfully: "تمت إضافة الفئة بنجاح",
    categorySaveFailed: "فشل حفظ الفئة",
    confirmDelete: "تأكيد مسح",
    deleteConfirmMessage: "هل أنت متأكد من مسح  ",
    delete: "إمسح",
    thisCategory: "هذه الفئة",
    categoryDeletedSuccessfully: "تم مسح الفئة بنجاح",
    categoryDeleteFailed: "فشل مسح الفئة",
    // dashboard/products
    productsManagement: "إدارة المنتجات",
    products: "المنتجات",
    productsList: "قائمة المنتجات",
    importProducts: "استيراد المنتجات",
    exportProducts: "تصدير المنتجات",
    addProduct: "إضافة منتج جديد",
    productStatisticsOverview: "نظرة عامة على إحصائيات المنتجات",
    productsTable: "جدول المنتجات",
    outOfStock: "منتهية المخزون",
    lowStock: "متوفر بكمية قليلة",
    inStock: "متوفر في المخزون",
    totalProducts: "إجمالي المنتجات",
    lowStock: "المخزون المنخفض",
    totalValue: "القيمة الإجمالية",
    selectedItems: "عنصر(عناصر) محددة",
    deleteSelectedItems: "حذف العناصر المحددة",    
    deleteSelected: "إمسح المحدد",
    searchProduct: "البحث عن المنتجات بالاسم...",
    selectStatusFilter: "إختيار فلتر الحالة",
    selectCategoryFilter: "إختيار فلتر الفئة",
    allStatus: "كل الحالات",
    applyMoreFilters: "تطبيق المزيد من المرشحات",
    moreFilters: "المزيد من المرشحات",
    product: 'المنتج',
    category: 'الفئة',
    price: 'السعر',
    EGP: "جنيه",
    stock: 'المخزون',
    featured: 'مُميَّز',
    actions: 'الإجراءات',
    ProductsList: "قائمة المنتجات",
    productsSubtitle: "قم بإدارة مخزون المنتجات وتتبع الأداء",
    isFeatured: "مُميَّز",
    notFeatured: "غير مُميَّز",
    productAddedAtDate: "تم إضافة المنتج في تاريخ",
    onSale: "للبيع بسعر مخفض",
    notOnSale: "بالسعر العادي",
    noProductsFound: "لا توجد منتجات",
    productsCaptions: "قائمة المنتجات المتاحة مع تفاصيل مثل الفئة والسعر وحالة المخزون.",
    productDetails: "تفاصيل المنتج",
    viewDetails: 'عرض التفاصيل',
    editProduct: 'تعديل المنتج',
    viewDetailsFor: 'عرض التفاصيل لـ',
    outOfStockInactiveWarningProduct: "هذا المنتج غير متوفر في المخزون أو غير نشط",
    someProductsHaveMixedStatus: "بعض المنتجات لديها حالة مختلطة. يرجى مراجعة قبل المتابعة.",
    productsActivatedSuccessfully: "تم تفعيل المنتجات بنجاح",
    productsDeactivatedSuccessfully: "تم إلغاء تفعيل الموردين بنجاح",
    productsPagination: "تسلسل المنتجات في الجدول",
    // dashboard/products/[id]
    productNotFound: "المنتج غير موجود",
    addedOn: "تم إضافته في",
    updatedOn: "تم تحديثه في",
    productOrders: "طلبات المنتج",
    productInformation: "معلومات المنتج",
    productDescription: "وصف المنتج",
    vendorInfo: "معلومات البائع",
    additionalInfo: "معلومات إضافية",
    createdBy: "تم إنشاؤه بواسطة",
    updatedBy: "تم تحديثه بواسطة",
    unknown: "غير معروف",
    isOnSale: "للبيع بسعر مخفض",
    yes: "نعم",
    no: "لا",
    salePrice: "سعر التخفيض",
    saleStart: "تاريخ بدء التخفيض",
    saleEnd: "تاريخ انتهاء التخفيض",
    tags: "العلامات",
    noTags: "لا توجد علامات",
    productUpdatedSuccessfully: "تم تحديث المنتج بنجاح",
    productAddedSuccessfully: "تم إضافة المنتج بنجاح",
    productSaveFailed: "فشل حفظ المنتج",
    selectAllProducts: "تحديد جميع المنتجات",    
    addProduct: "إضافة منتج جديد",
    editProduct: "تعديل المنتج",
    productStatusUpdatedSuccessfully: "تم تحديث حالة المنتج بنجاح",
    productImage: "صورة المنتج",
    productNameEn: "اسم المنتج (بالإنجليزية)",
    productNameAr: "اسم المنتج (بالعربية)",
    productPrice: "سعر المنتج",
    productStock: "مخزون المنتج",
    productCategory: "فئة المنتج",
    productDescriptionEn: "وصف المنتج (بالإنجليزية)",
    productDescriptionAr: "وصف المنتج (بالعربية)",
    productTags: "علامات المنتج",
    productVendor: "بائع المنتج",
    productIsActive: "المنتج نشط",
    productIsFeatured: "المنتج مميز",
    productIsOnSale: "المنتج معروض للبيع بسعر مخفض",
    productSalePrice: "سعر التخفيض للمنتج",
    productSaleStart: "تاريخ بدء التخفيض للمنتج",
    productSaleEnd: "تاريخ انتهاء التخفيض للمنتج",
    notSet: "لم يتم إضافة تاريخ",
    // validation messages
    productNameLength: "يجب أن يتراوح اسم المنتج بين 3 و 50 حرفًا",
    productDescriptionLength: "يجب أن يتراوح وصف المنتج بين 10 و 500 حرفًا",
    productImageRequired: "صورة المنتج مطلوبة",
    productNameEnRequired: "اسم المنتج (بالإنجليزية) مطلوب",
    productNameArRequired: "اسم المنتج (بالعربية) مطلوب",
    productPriceRequired: "سعر المنتج مطلوب",
    priceNumber: "يجب أن يكون السعر رقمًا صالحًا",
    priceMin: "يجب أن يكون السعر على الأقل 0",
    productStockRequired: "مخزون المنتج مطلوب",
    stockNumber: "يجب أن يكون المخزون رقمًا صالحًا",
    stockMin: "يجب أن يكون المخزون على الأقل 0",
    productCategoryRequired: "فئة المنتج مطلوبة",
    productDescriptionEnRequired: "وصف المنتج (بالإنجليزية) مطلوب",
    productDescriptionArRequired: "وصف المنتج (بالعربية) مطلوب",    
    productVendorRequired: "بائع المنتج مطلوب",
    salePriceValid: "سعر التخفيض يجب أن يكون رقماً صحيحاً",
    salePriceMin: "يجب أن يكون سعر التخفيض على الأقل 0",
    productSalePriceRequired: "سعر التخفيض للمنتج مطلوب عند وجود تخفيض",
    saleStartRequired: "تاريخ بداية التخفيض مطلوب عند وجود تخفيض",
    saleEndRequired: "تاريخ انتهاء التخفيض مطلوب عند وجود تخفيض",
    saleEndAfterStart: "تاريخ انتهاء التخفيض يجب أن يكون بعد تاريخ البداية",
    productTagsRequired: "علامات المنتج مطلوبة",
    productUpdatedSuccessfully: "تم تحديث المنتج بنجاح",
    productAddedSuccessfully: "تم إضافة المنتج بنجاح",
    productSaveFailed: "فشل حفظ المنتج",
    confirmDeleteProduct: "تأكيد مسح المنتج",
    deleteProductConfirmMessage: "هل أنت متأكد من مسح المنتج ",
    deleteProduct: "مسح المنتج",
    productDeletedSuccessfully: "تم مسح المنتج بنجاح",
    productDeleteFailed: "فشل مسح المنتج",
    selectCategory: "اختر الفئة",
    selectVendor: "اختر البائع",
    noVendorsFound: "لا يوجد موردون", 
    addTags: "إضافة علامات",
    typeAndPressEnter: "اكتب واضغط Enter لإضافة علامات",
    pressEnterOrCommaToAddTag: "اضغط Enter أو فاصلة لإضافة علامة",
    tagMinLength: "العلامة يجب أن تكون على الأقل 2 حرف",
    tagMaxLength: "العلامة يجب أن تكون على الأكثر 30 حرف",
    tagInvalidCharacters: "العلامات يمكن أن تحتوي فقط على أحرف، أرقام، مسافات، وهذه الرموز: - _ &",
    tagsMaxCount: "يمكنك إضافة ما يصل إلى 10 علامات",
    tagsUniqueError: "العلامات يجب أن تكون فريدة",
    tagsLengthTotalError: "إجمالي طول جميع العلامات يجب ألا يتجاوز 200 حرف",
    // dashboard/vendors
    vendorsManagement: "إدارة الموردين",
    vendors: "الموردون",
    vendorsList: "قائمة الموردين",
    vendorsSubtitle: "إدارة وعرض تفاصيل الموردين ونشاطاتهم",
    addVendor: "إضافة مورد",
    searchVendor: "ابحث عن مورد",
    vendorsTable: "جدول الموردين",
    selectAllVendors: "تحديد جميع الموردين",
    vendorName: "اسم المورد",
    contactPhone: "رقم هاتف المورد",
    location: "الموقع",
    aboutVendor: "عن المورد",
    socialLinks: "روابط التواصل الاجتماعي",
    facebook: "فيسبوك",
    instagram: "انستجرام",
    openFacebookPageFor: "افتح صفحة الفيسبوك لـ",
    openInstagramPageFor: "افتح صفحة إنستغرام لـ",
    noFaceBookAccount: "لا يوجد حساب فيسبوك",
    noInstagramAccount: "لا يوجد حساب إنستغرام",
    noSocialLinks: "لا توجد روابط اجتماعية",
    vendorAddedAtDate: "تم إضافة المورد في",
    noContactPhone: "لا يوجد رقم اتصال",
    noLocation: "لا يوجد موقع",
    noData: "لا يوجد وصف",
    vendorUpdatedSuccessfully: "تم تحديث المورد بنجاح",
    vendorAddedSuccessfully: "تمت إضافة المورد بنجاح",
    vendorSaveFailed: "فشل حفظ المورد",
    someVendorsHaveMixedStatus: "بعض الموردين لديهم حالة مختلطة. يرجى مراجعة قبل المتابعة.",
    vendorsActivatedSuccessfully: "تم تفعيل الموردين بنجاح",
    vendorsDeactivatedSuccessfully: "تم إلغاء تفعيل الموردين بنجاح",
    bulkToggleFailed: "فشل التحديث الجماعي",
    activateSelected: "تفعيل المحدد",
    deactivateSelected: "إلغاء تفعيل المحدد",
    mixedStatusWarning: "بعض الموردين لديهم حالة مختلطة",
    vendorsPagination: "تسلسل الموردين في الجدول",
    // dashboard/vendors/[id]
    vendorDetails: "تفاصيل المورد",
    vendorNotFound: "المورد غير موجود",
    vendorInformation: "معلومات المورد",
    editVendor: "تعديل المورد",
    vendorStatusUpdatedSuccessfully: "تم تحديث حالة المورد بنجاح",
    inactiveWarningVendor: "هذا المورد غير نشط",
    // Validation messages
    vendorNameLength: "يجب أن يكون اسم المورد بين 3 و50 حرفًا",
    vendorNameRequired: "اسم المورد مطلوب",
    countryCodeRequired: "رمز الدولة مطلوب",
    vendorLocationLength: "يجب أن يكون موقع المورد بين 3 و100 حرف",
    aboutVendorLength: "يجب أن يكون وصف المورد بين 10 و500 حرف",
    invalidFacebookUrl: "رابط فيسبوك غير صالح",
    invalidInstagramUrl: "رابط إنستغرام غير صالح",  
    // dashboard/shipping zones
    shippingZonesManagement: "إدارة مناطق الشحن",
    shippingZones: "مناطق الشحن",
    shippingZonesList: "قائمة مناطق الشحن",
    shippingZonesSubtitle: "إدارة مناطق الشحن وتكاليف الشحن المرتبطة بها",
    addZone: "إضافة منطقة شحن جديدة",
    editZone: "تعديل منطقة الشحن",
    searchZonesByNameOrZip: "ابحث في المناطق بالاسم أو الرمز البريدي",
    zoneName: "اسم المنطقة",
    zipCodes: "الرموز البريدية",
    cityNames: "أسماء المدن",
    shippingFee: "رسوم الشحن",
    taxRate: "معدل الضريبة",
    noZonesFound: "لا توجد مناطق شحن",
    shippingZoneAddedAtDate: "تمت إضافة منطقة الشحن في",
    shippingZoneUpdatedSuccessfully: "تم تحديث منطقة الشحن بنجاح",
    shippingZoneAddedSuccessfully: "تمت إضافة منطقة الشحن بنجاح",
    shippingZoneSaveFailed: "فشل حفظ منطقة الشحن",
    zonesActivatedSuccessfully: "مناطق الشحن تم تفعيلها بنجاح",
    zonesDeactivatedSuccessfully: "مناطق الشحن تم إلغاء تفعيلها بنجاح",
    mixedZonesStatusWarning: "مناطق الشحن لديها حالة مختلطة",
    someZonesHaveMixedStatus: "بعض مناطق الشحن لديها حالة مختلطة. يرجى مراجعة قبل المتابعة.",  
    zoneNameInEnglish: "اسم المنطقة (بالإنجليزية)",
    zoneNameInArabic: "اسم المنطقة (بالعربية)",
    addZipCode: "إضافة رمز بريدي",
    typeAndPressEnterToZipCode: "اكتب واضغط Enter لإضافة رمز بريدي",
    pressEnterOrCommaToAddZipCode: "اضغط Enter أو فاصلة لإضافة رمز بريدي",
    cities: "المدن",
    typeCityNameInEnglish: "اكتب اسم المدينة (بالإنجليزية)",
    typeCityNameInArabic: "اكتب اسم المدينة (بالعربية)",
    shippingFee: "رسوم الشحن",
    taxRateHelperText: "أدخل معدل الضريبة/القيمة المضافة كعدد عشري (مثال: 0.14 لـ 14%)",
    taxRateTooltip: "أدخل قيمة بين 0 و 1 (مثال: 0.14 = 14%)",
    shippingZoneDetails: "تفاصيل منطقة الشحن",
    zoneNotFound: "منطقة الشحن غير موجودة",
    zoneInformation: "معلومات منطقة الشحن",
    aboutZone: "عن المنطقة",
    noZipCodes: "لا توجد رموز بريدية",
    noCities: "لا توجد مدن",
    inactiveWarningZone: "هذه منطقة الشحن غير نشطة",
    zoneStatusUpdatedSuccessfully: "تم تحديث حالة منطقة الشحن بنجاح",
    // validation messages
    shippingZoneNameEnRequired: "منطقة الشحن (بالإنجليزية) مطلوبة",
    shippingZoneNameArRequired: "منطقة الشحن (بالعربية) مطلوبة",
    shippingZoneNameLength: "يجب أن يكون اسم منطقة الشحن بين 3 و50 حرفًا",
    invalidZipCodeFormat: "صيغة الرمز البريدي غير صالحة",
    duplicateZipCodes: "الرموز البريدية المكررة غير مسموح بها",
    cityNameEnLength: "اسم المدينة (بالإنجليزية) يجب أن يكون بين 2 و 50 حرفًا",
    cityNameArLength: "اسم المدينة (بالعربية) يجب أن يكون بين 2 و 50 حرفًا",
    shippingFeeRequired: "رسوم الشحن مطلوبة",
    shippingFeeNumber: "رسوم الشحن يجب أن تكون رقمًا صالحًا",
    shippingFeeMin: "رسوم الشحن يجب أن تكون على الأقل 0",
    taxRateNumber: "معدل الضريبة يجب أن يكون رقمًا صالحًا",
    taxRateMin: "معدل الضريبة يجب أن يكون على الأقل 0",
    taxRateMax: "معدل الضريبة يجب أن يكون بحد أقصى 1",
    // cart page
    failedToUpdateCart: "فشل تحديث العربة",
    itemRemovedFromCart: "تمت إزالة العنصر من العربة",
    decreaseQuantity: "قلل كمية",
    increaseQuantity: "زد كمية",
    failedToRemoveItem: "فشل إزالة العنصر",
    pleaseLoginToCheckout: "يرجى تسجيل الدخول لإتمام الشراء",
    yourCartIsEmpty: "عربتك فارغة",
    continueShopping: "استمر في التسوق",
    shoppingCart: "عربة التسوق",
    total: "الإجمالي",
    itemsInCart: "عنصر(عناصر) في العربة",
    proceedToCheckout: "المتابعة إلى الدفع",
    isAddedToCart: "تمت إضافته إلى العربة",
    errorAddingToCart: "خطأ في إضافة إلى العربة",
    // checkout
    checkout: "الدفع",
    shippingInformation: "معلومات الشحن",
    fullName: "الاسم الكامل",
    paymentMethod: "طريقة الدفع",
    cashOnDelivery: "الدفع عند الاستلام",
    onlinePayment: "الدفع عبر الإنترنت",
    orderSummary: "ملخص الطلب",
    shippingTo: "الشحن إلى",
    subtotal: "المجموع الفرعي",
    shipping: "الشحن",
    tax: "الضريبة",
    total: "الإجمالي",
    qty: "الكمية",
    processing: "جار المعالجة...",
    placeOrder: "إتمام الطلب",
    orderPlacedSuccessfully: "تم إتمام الطلب بنجاح",
    failedToPlaceOrder: "فشل إتمام الطلب",
    networkError: "خطأ في الشبكة، يرجى المحاولة مرة أخرى",
    useSavedAddress: "استخدم عنوان محفوظ",
    savedAddresses: "العناوين المحفوظة",
    enterNewAddress: "أدخل عنوان جديد",
    // Roles Management
    rolesManagement: "إدارة الأدوار",
    roles: "الأدوار",
    rolesList: "قائمة الأدوار",
    rolesSubtitle: "إدارة أدوار المستخدمين والأذونات",
    addRole: "إضافة دور جديد",
    editRole: "تعديل الدور",
    searchRoles: "ابحث عن الأدوار بالاسم...",
    noRolesFound: "لا توجد أدوار",
    permissions: "الأذونات",
    roleName: "اسم الدور",
    roleUpdatedSuccessfully: "تم تحديث الدور بنجاح",
    roleAddedSuccessfully: "تمت إضافة الدور بنجاح",
    roleSaveFailed: "فشل حفظ الدور",
    managePermissions: "إدارة الأذونات",
    for: "لـ",
    noActionsFound: "لا توجد أذونات متاحة",
    actionsAssignedSuccessfully: "تم تعيين الأذونات بنجاح",
    actionsRemovedSuccessfully: "تمت إزالة الأذونات بنجاح",
    noPermissionsChanged: "لم تتغير الأذونات",
    failedToUpdatePermissions: "فشل تحديث الأذونات",
    // validation messages
    roleNameLength: "يجب أن يكون اسم الدور بين 3 و50 حرفًا",
    roleNameRequired: "اسم الدور مطلوب",
    // Warehouse Management
    warehousesManagement: "إدارة المستودعات",
    warehouses: "المستودعات",
    warehousesList: "قائمة المستودعات",
    warehousesSubtitle: "إدارة مستودعاتك",
    addWarehouse: "إضافة مستودع جديد",
    editWarehouse: "تعديل المستودع",
    searchWarehousesByName: "ابحث عن المستودعات بالاسم...",
    warehouseName: "اسم المستودع",
    warehouseLocation: "الموقع",
    manager: "المدير",
    noWarehousesFound: "لا توجد مستودعات",
    addWarehouse: "إضافة مستودع جديد",
    editWarehouse: "تعديل المستودع",
    phone: "الهاتف",
    contactPerson: "الشخص المسؤول",
    capacity: "السعة",
    noContactEmail: "لا يوجد بريد إلكتروني للاتصال",
    noContactPerson: "لا يوجد شخص مسؤول للاتصال",
    warehouseManager: "مدير المستودع",
    aboutWarehouse: "عن المستودع",
    warehouseAddedAtDate: "تمت إضافة المستودع في",
    warehouseUpdatedSuccessfully: "تم تحديث المستودع بنجاح",
    warehouseAddedSuccessfully: "تمت إضافة المستودع بنجاح",
    warehouseSaveFailed: "فشل حفظ المستودع",
    someWarehousesHaveMixedStatus: "بعض المستودعات لديها حالة مختلطة. يرجى مراجعة قبل المتابعة.",
    warehousesActivatedSuccessfully: "تم تفعيل المستودعات بنجاح",
    warehousesDeactivatedSuccessfully: "تم تعطيل المستودعات بنجاح",
    warehouseSaveFailed: "فشل حفظ المستودع",
    warehousesPagination: "تجميع جدول المستودعات",
    warehouseDetails: "تفاصيل المستودع",
    warehouseNotFound: "المستودع غير موجود",
    warehouseInformation: "معلومات المستودع",
    warehouseAddress: "عنوان المستودع",
    storageCapacity: "سعة التخزين",
    units: "الوحدات",
    available: "متاح",
    totalCapacity: "السعة الإجمالية",
    inactiveWarningWarehouse: "هذا المستودع غير نشط حالياً",
    warehouseStatusUpdatedSuccessfully: "تم تحديث حالة المستودع بنجاح",
    addressInfo: "معلومات العنوان",
    basicInfo: "معلومات أساسية",
    // Validation messages
    warehouseNameLength: "Warehouse name must be between 3 and 50 characters",
    warehouseNameRequired: "Warehouse name is required",
    streetLength: "Street must be between 3 and 100 characters",
    streetRequired: "Street is required",
    cityLength: "City must be between 2 and 50 characters",
    cityRequired: "City is required",
    stateLength: "State must be between 2 and 50 characters",
    stateRequired: "State is required",
    invalidPhone: "Invalid phone number",
    contactPersonLength: "Contact person name must be between 3 and 50 characters",
    capacityPositive: "Capacity must be a positive number"
}

  