// localization/en.js
export const en = {
    english: "English",
    arabic: "Arabic",
    headTitle: "Farmer's Market",
    home: "Home",
    about: "About",
    profile: "Profile",
    orders: "My Orders",
    cart: "Cart",
    login: "Login",
    addAccount: "Add Another Account",
    settings: "Settings",
    logout: "Logout",
    loading: "Loading...",
    tryAgain: "Try Again",
    somthingWentWrong: "Something went wrong!",
    // home page
    "From Our Store to Your Door": "From Our Store to Your Door",
    "Fast & smooth shopping experience": "Fast & smooth shopping experience for the household.",
    prevArrow: "Previous",
    nextArrow: "Next",
    order: "Order Now",
    featuredProducts: "Featured Products",
    topDeals: "Top Deals",
    bestSellers: "Best Sellers",
    newArrivals: "New Arrivals",
    whyChooseUs: "Why Choose Us",
    allRightsReserved: " All Rights Reserved.",
    searchProductsOrCategories: "Search products or categories...",
    by: "by",
    viewAllFeatured: "View All Featured",
    viewAllDeals: "View All Deals",
    viewAllBestSellers: "View All Best Sellers",
    viewAllNewArrivals: "View All New Arrivals",
    new: "New",
    addToCart: "Add to Cart",
    off: "% OFF",
    noResultsFound: "No results found",
    // product/slug page
    uncategorized: "Uncategorized",
    quantity: "Quantity",
    soldBy: "Sold by",
    relatedProducts: "Related Products",
    shopByCategory: "Shop by Category",
    // category/[slug] page
    categoryHeaderDescription: "Explore our wide range of fresh and organic products in this category.",
    noProductsInCategory: "No products found in this category.",
    loadMore: "Load More",
    endOfResults: "End of Results",
    leftInStock: "left in stock",
    outOfStock: "Out of Stock",
    // login
    welcomeMsg: "Welcome to Farmer's Market!",
    slogan: "Fresh, local, and sustainable—sign in to explore the best produce.",
    signUpQuestion: "Don't have an account?",
    register: "Register",
    email: "Email",
    password: "Password",
    rememberMe: "Remember Me",
    hidePassword: "Hide Password",
    showPassword: "Show Password",
    // login validation
    loginSuccessfullMsg: "Login successful! Welcome back",
    invalidEmail: "Invalid Email",
    emailRequired: "Email is required",
    passwordLength: "Password must be at least 8 characters",
    passwordRequired: "Password is required",
    // register
    firstName: "First Name",
    lastName: "Last Name",
    phoneNumber: "Phone Number",
    enterPhoneNumber: "Enter your phone number",
    alreadyHaveAnAccountQuestion: "Already have an account ?",
    // register validation
    registrationSuccessfullMsg: "Registration successful! Please Login.",
    nameLength: "Name must be between 3 and 30 characters",
    nameRegexError: "Name can only contain letters, numbers, spaces, hyphens, and underscores",
    nameRequired: "Name is required",
    invalidEmail: "Please enter a valid email address",
    emailRequired: "Email is required",
    passwordRegexError: "Password must contain at least one letter and one special character.",
    phoneNumberRequired: "Phone number is required",
    phoneNumberRegex: "Phone number must start with 010, 011, 012, or 015 and be 11 digits long",
    // dashboard
    dashboard: "Dashboard",
    welcomeToDashboardMsg: "Welcome to the Dashboard",
    dashboardSlogan: "Here you can see your stats, recent activity, and more.",
    stats: "Stats",
    recentActivity: "Recent Activity",
    recentOrders: "Recent Orders",
    recentReviews: "Recent Reviews",
    recentMessages: "Recent Messages",
    recentProducts: "Recent Products",
    recentUsers: "Recent Users",
    recentOrders: "Recent Orders",
    languageSelector: "Language Selector",
    selectLanguage: "Select Language",
    openToSwitchLanguage: "Click to switch language",
    // dashboard/customers
    customersManagement: "Customers Management",
    customers: "Customers",
    customersList: "Customers List",
    createdAt: "Created At",
    search: "Search",
    status: "Status",
    startDate: "Start Date",
    endDate: "End Date",
    all: "All",
    active: "Active",
    inactive: "Inactive",
    pleaseSubmitToSearch: "Please submit the form to search for customers",
    noCustomersFound: "No customers found",
    submit: "Submit",
    reset: "Reset",
    dataRetreivedSuccessfully: "Data retrieved successfully",
    customersDescription: "Manage your customer accounts and view customer details.",
    view: "View",
    customersPagination: "Customers table pagination",
    // dashboard/customers/[id]
    customerNotFound: "Customer not found",
    joinedOn: "Joined On",
    goBack: "Go Back",
    customerProfile: "Customer Profile",
    customerDetails: "Customer Details",
    basicInfo: "Basic Information",
    customerOrders: "Customer Orders",
    contactInformation: "Contact Information",
    addressInformation: "Address Information",
    shippingAddress: "Shipping Address",
    billingAddress: "Billing Address",
    noDefaultShippingAddress: "No default shipping address set",
    noDefaultBillingAddress: "No default billing address set",
    noAddressProvided: "No address provided",
    orderNumber: "Order Number",
    orderDate: "Order Date",
    orderStatus: "Order Status",
    orderTotal: "Order Total",
    orderDetails: "Order Details",
    orderItems: "Order Items",
    orderQuantity: "Quantity",
    orderPrice: "Price",
    orderSubtotal: "Subtotal",
    orderShipping: "Shipping",
    orderTax: "Tax",
    orderTotalAmount: "Total Amount",
    orderActions: "Actions",
    noOrders: "No orders found for this customer",
    updating: "Updating...",
    deactivate: "Deactivate",
    activate: "Activate",
    userStatusUpdatedSuccessfully: "User status updated successfully",
    // Profile
    myAccount: "My Account",
    personalInfo: "Personal Information",
    saveChanges: "Save Changes",
    profileUpdated: "Profile updated successfully",
    profileUpdateFailed: "Profile update failed",
    addresses: "Addresses",
    editAddress: "Edit Address",
    addNewAddress: "Add New Address",
    addressDetails: "Address Details",
    edit: "Edit",
    viewDetails: "View Details",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "Zip Code",
    country: "Country",
    isDefaultShipping: "Is Default Shipping",
    isDefaultBilling: "Is Default Billing",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    defaultShipping: "Default Shipping",
    defaultBilling: "Default Billing",
    // profile validation
    streetLength: "Street must be between 3 and 100 characters",
    streetRequired: "Street is required",
    cityLength: "City must be between 2 and 50 characters",
    cityRequired: "City is required",
    stateLength: "State must be between 2 and 50 characters",
    zipCodeLength: "Zip Code must be between 5 and 10 characters",
    zipCodeRequired: "Zip Code is required",
    countryRequired: "Country is required",
    addressSavedSuccessfully: "Address saved successfully",
    addressSaveFailed: "Address save failed",
    addressRemovedSuccessfully: "Address removed successfully",
    addressRemoveFailed: "Address remove failed",
    // dashboard/categories
    categoriesManagement: "Categories Management",
    categories: "Categories",
    categoriesList: "Categories List",
    noCategoriesFound: "No Categories Found",
    addCategory: "Add New Category",
    editCategory: "Edit Category",
    deleteCategory: "Delete Category",
    searchCategory: "Search for a Category",
    categoryNameEn: "Category Name (English)",
    categoryNameAr: "Category Name (Arabic)",
    textColor: "Text Color",
    categoryImage: "Category Image",
    uploadImage: "Upload Image",
    // validation messages
    categoryNameEnRequired: "Category name (English) is required",
    categoryNameArRequired: "Category name (Arabic) is required",
    invalidImageFormat: "Invalid image format. Allowed formats: jpg, jpeg, png, gif, webp",
    categoryNameLength: "Category name must be between 3 and 50 characters",
    categoryNameRegexError: "Category name can only contain letters, numbers, spaces, and these symbols: - _ .",
    imageRequired: "Category image is required",
    categoryUpdatedSuccessfully: "Category updated successfully",
    categoryAddedSuccessfully: "Category added successfully",
    categorySaveFailed: "Category save failed",
    confirmDelete: "Confirm Delete",
    deleteConfirmMessage: "Are you sure you want to delete ",
    delete: "Delete",
    thisCategory: "this category",
    categoryDeletedSuccessfully: "Category deleted successfully",
    categoryDeleteFailed: "Category delete failed",
    // dashboard/products
    productsManagement: "Products Management",
    products: "Products",
    productsList: "Products List",
    importProducts: "Import Products",
    exportProducts: "Export Products",
    addProduct: "Add Product",
    productStatisticsOverview:"Product statistics overview",
    productsTable: "Products Table",
    outOfStock: "Out of Stock",
    lowStock: "Low Stock",
    inStock: "In Stock",
    totalProducts: "Total Products",
    totalValue: "Total Value",
    selectedItems: "item(s) selected",
    deleteSelectedItems: "Delete selected items",
    deleteSelected: "Delete Selected",
    searchProduct: "Search products by name...",
    selectStatusFilter: "Select status filter",
    selectCategoryFilter: "Select category filter",
    allStatus: "All Status",
    applyMoreFilters: "Apply more filters",
    moreFilters: "More Filters",
    product: 'Product',
    category: 'Category',
    price: 'Price',
    EGP: "EGP",
    stock: 'Stock',
    featured: 'Featured',
    actions: 'Actions',
    ProductsList: "Products List",
    productsSubtitle: "Manage your product inventory and track performance",
    isFeatured: "Is Featured",
    notFeatured: "Not Featured",
    productAddedAtDate: "Product added at",
    onSale: "On Sale",
    notOnSale: "Not On Sale",
    noProductsFound: "No products found",
    productsCaptions: "A list of available products with details such as category, price, and stock status.",
    productDetails: "Product Details",
    viewDetails: 'View Details',
    editProduct: 'Edit Product',
    viewDetailsFor: 'View Details for',
    outOfStockInactiveWarningProduct: "This product is inActive or out of stock",
    someProductsHaveMixedStatus: "Some products have mixed status. Please review before proceeding.",
    productsActivatedSuccessfully: "Products activated successfully",
    productsDeactivatedSuccessfully: "Products deactivated successfully",
    productsPagination: "Products table pagination",
    // dashboard/products/[id]
    productNotFound: "Product not found",
    addedOn: "Added On",
    updatedOn: "Updated On",
    productOrders: "Product Orders",
    productInformation: "Product Information",
    productDescription: "Product Description",
    vendorInfo: "Vendor Information",
    additionalInfo: "Additional Information",
    createdBy: "Created By",
    updatedBy: "Updated By",
    unknown: "Unknown",
    isOnSale: "Is On Sale",
    yes: "Yes",
    no: "No",
    salePrice: "Sale Price",
    saleStart: "Sale Start",
    saleEnd: "Sale End",
    tags: "Tags",
    noTags: "No Tags",
    productUpdatedSuccessfully: "Product updated successfully",
    productAddedSuccessfully: "Product added successfully",
    productSaveFailed: "Product save failed",
    selectAllProducts: "Select All Products",
    addProduct: "Add New Product",
    editProduct: "Edit Product",
    productStatusUpdatedSuccessfully: "Product status updated successfully",
    productImage: "Product Image",
    productNameEn: "Product Name (English)",
    productNameAr: "Product Name (Arabic)",
    productPrice: "Product Price",
    productStock: "Product Stock",
    productCategory: "Product Category",
    productDescriptionEn: "Product Description (English)",
    productDescriptionAr: "Product Description (Arabic)",
    productTags: "Product Tags",
    productVendor: "Product Vendor",
    productIsActive: "Product is Active",
    productIsFeatured: "Product is Featured",
    productIsOnSale: "Product is On Sale",
    productSalePrice: "Product Sale Price",
    productSaleStart: "Product Sale Start",
    productSaleEnd: "Product Sale End",
    notSet: "Not Set",
    // validation messages
    productNameLength: "Product name must be between 3 and 50 characters",
    productDescriptionLength: "Product description must be between 10 and 500 characters",
    productImageRequired: "Product image is required",
    productNameEnRequired: "Product name (English) is required",
    productNameArRequired: "Product name (Arabic) is required",
    productPriceRequired: "Product price is required",
    priceNumber: "Price must be a valid number",
    priceMin: "Price must be at least 0",
    productStockRequired: "Product stock is required",
    stockNumber: "Stock must be a valid number",
    stockMin: "Stock must be at least 0",
    productCategoryRequired: "Product category is required",
    productDescriptionEnRequired: "Product description (English) is required",
    productDescriptionArRequired: "Product description (Arabic) is required",
    productVendorRequired: "Product vendor is required",
    salePriceValid: "Sale price must be a valid number",
    salePriceMin: "Sale price must be at least 0",
    productSalePriceRequired: "Product sale price is required when on sale",
    saleStartDateRequired: "Sale start date is requred",
    saleEndDateRequired: "Sale end date is required when on sale",
    saleEndAfterStart: "Sale end date must be after start date",
    productTagsRequired: "Product tags are required",
    productUpdatedSuccessfully: "Product updated successfully",
    productAddedSuccessfully: "Product added successfully",
    productSaveFailed: "Product save failed",
    confirmDeleteProduct: "Confirm Delete Product",
    deleteProductConfirmMessage: "Are you sure you want to delete the product ",
    deleteProduct: "Delete Product",
    productDeletedSuccessfully: "Product deleted successfully",
    productDeleteFailed: "Product delete failed",
    selectCategory: "Select Category",
    selectVendor: "Select Vendor",
    noVendorsFound: "No vendors found", 
    addTags: "Add Tags",
    typeAndPressEnter: "Type and press Enter to add tags",
    pressEnterOrCommaToAddTag: "Press Enter or Comma to add a tag",
    tagMinLength: "Tag must be at least 2 characters",
    tagMaxLength: "Tag must be at most 30 characters",
    tagInvalidCharacters: "Tags can only contain letters, numbers, spaces, and these symbols: - _ &",
    tagsMaxCount: "You can add up to 10 tags",
    tagsUniqueError: "Tags must be unique",
    tagsLengthTotalError: "Total length of all tags must not exceed 200 characters",
    // dashboard/vendors
    vendorsManagement: "Vendors Management",
    vendors: "Vendors",
    vendorsList: "Vendors List",
    vendorsSubtitle: "Manage your vendors",
    addVendor: "Add New Vendor",
    searchVendor: "Search vendors by name...",
    vendorsTable: "Vendors table",
    selectAllVendors: "Select All Vendors",
    vendorName: "Vendor Name",
    contactPhone: "Vendor Phone Number",
    location: "Location",
    aboutVendor: "About Vendor",
    socialLinks: "Social Links",
    facebook: "Facebook",
    instagram: "Instagram",
    openFacebookPageFor: "Open Facebook page for",
    openInstagramPageFor: "Open Instagram page for",
    noFaceBookAccount: "No Facebook",
    noInstagramAccount: "No Instagram",
    noSocialLinks: "No social links",
    vendorAddedAtDate: "Vendor added at",
    noContactPhone: "No contact phone",
    noLocation: "No location",
    noData: "No Data",
    vendorUpdatedSuccessfully: "Vendor updated successfully",
    vendorAddedSuccessfully: "Vendor added successfully",
    vendorSaveFailed: "Vendor save failed",
    someVendorsHaveMixedStatus: "Some vendors have mixed status. Please review before proceeding.",
    vendorsActivatedSuccessfully: "Vendors activated successfully",
    vendorsDeactivatedSuccessfully: "Vendors deactivated successfully",
    bulkToggleFailed: "Bulk toggle failed",
    activateSelected: "Activate Selected",
    deactivateSelected: "Deactivate Selected",
    mixedStatusWarning: "Some vendors have mixed status",
    vendorsPagination: "Vendors table pagination",
    // dashboard/vendors/[id]
    vendorDetails: "Vendor Details",
    vendorNotFound: "Vendor not found",
    vendorInformation: "Vendor Information",
    editVendor: "Edit Vendor",
    vendorStatusUpdatedSuccessfully: "Vendor status updated successfully",
    inactiveWarningVendor: "This vendor is inactive",
    // Validation messages
    vendorNameLength: "Vendor name must be between 3 and 50 characters",
    vendorNameRequired: "Vendor name is required",
    countryCodeRequired: "Country code is required",
    vendorLocationLength: "Vendor location must be between 3 and 100 characters",
    aboutVendorLength: "Vendor description must be between 10 and 500 characters",
    invalidFacebookUrl: "Invalid Facebook URL",
    invalidInstagramUrl: "Invalid Instagram URL",
    // dashboard/shipping zones
    shippingZonesManagement: "Shipping Zones Management",
    shippingZones: "Shipping Zones",
    shippingZonesList: "Shipping Zones List",
    shippingZonesSubtitle: "Manage your shipping zones and fees",
    addZone: "Add New Shipping Zone",
    editZone: "Edit Shipping Zone",
    searchZonesByNameOrZip: "Search shipping zones by name or zip code...",
    zoneName: "Zone Name",
    zipCodes: "ZIP Codes",
    cityNames: "City Names",
    shippingFee: "Shipping Fee (EGP)",
    taxRate: "Tax Rate",
    noZonesFound: "No shipping zones found",
    shippingZoneAddedAtDate: "Shipping zone added at",
    shippingZoneUpdatedSuccessfully: "Shipping zone updated successfully",
    shippingZoneAddedSuccessfully: "Shipping zone added successfully",
    shippingZoneSaveFailed: "Shipping zone save failed",
    zonesActivatedSuccessfully: "Shipping zones activated successfully",
    zonesDeactivatedSuccessfully: "Shipping zones deactivated successfully",
    mixedZonesStatusWarning: "Some shipping zones have mixed status",
    someZonesHaveMixedStatus: "Some shipping zones have mixed status. Please review before proceeding.",
    zoneNameInEnglish: "Zone Name (English)",
    zoneNameInArabic: "Zone Name (Arabic)",
    addZipCode: "Add ZIP Code",
    typeAndPressEnterToZipCode: "Type and press Enter to add ZIP code",
    pressEnterOrCommaToAddZipCode: "Press Enter or Comma to add a ZIP code",
    cities: "Cities",
    typeCityNameInEnglish: "Type city name (English)",
    typeCityNameInArabic: "Type city name (Arabic)",
    shippingFee: "Shipping Fee",
    taxRateHelperText: "Enter VAT/Tax rate as decimal (e.g., 0.14 for 14%)",
    taxRateTooltip: "Enter a value between 0 and 1 (e.g., 0.14 = 14%)",
    shippingZoneDetails: "Shipping Zone Details",
    zoneNotFound: "Shipping zone not found",
    zoneInformation: "Zone Information",
    aboutZone: "About Zone",
    noZipCodes: "No ZIP codes",
    noCities: "No cities",
    inactiveWarningZone: "This Zone is inactive",
    zoneStatusUpdatedSuccessfully: "Shipping zone status updated successfully",
    // Validation messages
    shippingZoneNameEnRequired: "Shipping zone name (English) is required",
    shippingZoneNameArRequired: "Shipping zone name (Arabic) is required",
    shippingZoneNameLength: "Shipping zone name must be between 3 and 50 characters",
    invalidZipCodeFormat: "Invalid ZIP code format",
    duplicateZipCodes: "Duplicate ZIP codes are not allowed",
    cityNameEnLength: "City name (English) must be between 2 and 50 characters",
    cityNameArLength: "City name (Arabic) must be between 2 and 50 characters",
    shippingFeeRequired: "Shipping fee is required",
    shippingFeeNumber: "Shipping fee must be a valid number",
    shippingFeeMin: "Shipping fee must be at least 0",
    taxRateNumber: "Tax rate must be a valid number",
    taxRateMin: "Tax rate must be at least 0",
    taxRateMax: "Tax rate must be at most 1",
    // cart page
    failedToUpdateCart: "Failed to update cart",
    itemRemovedFromCart: "Item removed from cart",
    decreaseQuantity: "Decrease Quantity",
    increaseQuantity: "Increase Quantity",
    failedToRemoveItem: "Failed to remove item",
    pleaseLoginToCheckout: "Please login to checkout",
    yourCartIsEmpty: "Your cart is empty",
    continueShopping: "Continue Shopping",
    shoppingCart: "Shopping Cart",
    total: "Total",
    itemsInCart: "items in cart",
    proceedToCheckout: "Proceed to Checkout",
    isAddedToCart: "is added to cart",
    errorAddingToCart: "Error adding item to cart",
    // checkout
    checkout: "Checkout",
    shippingInformation: "Shipping Information",
    fullName: "Full Name",
    paymentMethod: "Payment Method",
    cashOnDelivery: "Cash on Delivery",
    onlinePayment: "Online Payment",
    orderSummary: "Order Summary",
    shippingTo: "Shipping to",
    subtotal: "Subtotal",
    shipping: "Shipping",
    tax: "Tax",
    total: "Total",
    qty: "Qty",
    processing: "Processing",
    placeOrder: "Place Order",
    orderPlacedSuccessfully: "Order placed successfully",
    failedToPlaceOrder: "Failed to place order",
    networkError: "Network error",
    useSavedAddress: "Use Saved Address",
    savedAddresses: "Saved Addresses",
    enterNewAddress: "Enter New Address",
};